name: pkgbuild import

on:
  workflow_dispatch:

env:
  GITHUB_USERNAME: dakkshesh07
  GITHUB_EMAIL: dakkshesh5@gmail.com
  GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

jobs:
  fetch:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-toolchains/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configuring git
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_EMAIL
          gh auth login --with-token <<< $GHUB_TOKEN
      - name: Fetch and Push
        run: |
          curl -fsSL "https://pkgbuild.com/~morganamilo/pacman-static/x86_64/bin/pacman-static" -o pacman-static && chmod +x pacman-static && mv pacman-static /usr/bin/
          pacman-static -S --needed --noconfirm curl ripgrep
          git clone https://"${GITHUB_USERNAME}":"${GHUB_TOKEN}"@github.com/AetherLinux/PKGBUILDS.git repo-dir
          cd repo-dir
          rm -rf *
          mv ../fetch.sh .
          bash fetch.sh
          git add -A
          git commit -asm "[skip ci] Import PKGBUILDs as of $(date '+%Y-%m-%d')"
          git push origin main -f
